# Generated by Django 4.0.2 on 2022-04-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loads', '0007_alter_load_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('truckNo', models.IntegerField()),
                ('pickupAddress', models.TextField()),
                ('timeIn', models.TimeField()),
                ('timeOut', models.TimeField()),
                ('deliveryAddress', models.TextField()),
                ('deliveryTimeIn', models.TimeField()),
                ('deliveryTimeOut', models.TimeField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('drivingHours', models.DecimalField(decimal_places=2, max_digits=3)),
                ('totalHours', models.DecimalField(decimal_places=2, max_digits=3)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loads.driver')),
            ],
        ),
    ]
