# Generated by Django 4.0.2 on 2022-04-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbook',
            old_name='deliveryAddress',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='logbook',
            old_name='deliveryTimeIn',
            new_name='delivery_timeOut',
        ),
        migrations.RenameField(
            model_name='logbook',
            old_name='deliveryTimeOut',
            new_name='delivery_timein',
        ),
        migrations.RenameField(
            model_name='logbook',
            old_name='drivingHours',
            new_name='driving_hours',
        ),
        migrations.RenameField(
            model_name='logbook',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='logbook',
            old_name='pickupAddress',
            new_name='pickup_address',
        ),
        migrations.RenameField(
            model_name='logbook',
            old_name='startTime',
            new_name='star_time',
        ),
        migrations.RenameField(
            model_name='logbook',
            old_name='timeIn',
            new_name='time_in',
        ),
        migrations.RenameField(
            model_name='logbook',
            old_name='timeOut',
            new_name='time_out',
        ),
        migrations.RenameField(
            model_name='logbook',
            old_name='totalHours',
            new_name='total_hours',
        ),
        migrations.RenameField(
            model_name='logbook',
            old_name='truckNo',
            new_name='truck_no',
        ),
    ]
