# Generated by Django 4.0.2 on 2022-04-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_rename_deliveryaddress_logbook_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='date',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='delivery_timeOut',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='delivery_timein',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='driving_hours',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='star_time',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='time_out',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='total_hours',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='truck_no',
        ),
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('truck_no', models.IntegerField()),
                ('pickup_address', models.TextField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('delivery_address', models.TextField()),
                ('delivery_timein', models.TimeField()),
                ('delivery_timeOut', models.TimeField()),
                ('star_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('driving_hours', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=3)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logbook.logbook')),
            ],
        ),
    ]
