# Generated by Django 4.0.2 on 2022-04-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_remove_logbook_date_remove_logbook_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbookentry',
            old_name='delivery_timeOut',
            new_name='delivery_timeout',
        ),
    ]
