# Generated by Django 4.0.2 on 2022-04-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_rename_delivery_timeout_logbookentry_delivery_timeout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbookentry',
            old_name='star_time',
            new_name='start_time',
        ),
    ]
