# Generated by Django 4.0.2 on 2022-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_rename_star_time_logbookentry_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='truck_no',
            field=models.IntegerField(blank=True),
        ),
    ]
