# Generated by Django 4.0.2 on 2022-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_alter_logbookentry_truck_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='delivery_timein',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='delivery_timeout',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='pickup_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='time_in',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='time_out',
            field=models.TimeField(blank=True),
        ),
    ]
