# Generated by Django 4.0.2 on 2022-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_alter_logbookentry_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='driving_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
