# Generated by Django 4.0.2 on 2022-04-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_alter_logbookentry_driving_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='delivery_timein',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='delivery_timeout',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='driving_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='truck_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
