# Generated by Django 4.0.2 on 2022-04-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_alter_logbookentry_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logbookentry',
            options={'ordering': ['id']},
        ),
    ]
