# Generated by Django 4.0.2 on 2022-02-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0002_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('N', 'Not Invoiced'), ('I', 'Invoiced'), ('P', 'Paid')], default='N', max_length=3),
        ),
    ]
