# Generated by Django 4.0.2 on 2022-02-18 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0005_loadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('N', 'Not Invoiced'), ('G', 'Generated'), ('I', 'Invoiced'), ('P', 'Paid')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='load',
            name='loaded_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadimage',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadimage', to='loads.load'),
        ),
    ]
