# Generated by Django 4.0.2 on 2022-03-30 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0006_alter_invoice_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LoadInvoice', to='loads.invoice'),
        ),
    ]
