# Generated by Django 4.0.4 on 2022-04-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loads', '0008_driver_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loads.driver')),
            ],
        ),
        migrations.CreateModel(
            name='LogbookEntry2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('truck_no', models.IntegerField(blank=True, null=True)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_timein', models.TimeField(blank=True, null=True)),
                ('delivery_timeout', models.TimeField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('driving_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logbook2.logbook2')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
