# Generated by Django 4.0.4 on 2022-04-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbookentry2',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='logbookentry2',
            name='delivery_timein',
        ),
        migrations.RemoveField(
            model_name='logbookentry2',
            name='delivery_timeout',
        ),
        migrations.RemoveField(
            model_name='logbookentry2',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='logbookentry2',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='logbookentry2',
            name='time_out',
        ),
    ]
