# Generated by Django 4.0.4 on 2022-04-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook2', '0002_remove_logbookentry2_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry2',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logbookentry2',
            name='driving_hours',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logbookentry2',
            name='end_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logbookentry2',
            name='logbook',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logbookentry2',
            name='start_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logbookentry2',
            name='total_hours',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logbookentry2',
            name='truck_no',
            field=models.CharField(max_length=255),
        ),
    ]
